sonar.projectKey=wesleykirkland_terraform-provider-urllo
sonar.organization=wesleykirkland

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/.terraform/**,examples/**,**/test_*.py

sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/test_*.py

sonar.go.coverage.reportPaths=coverage.out
sonar.python.coverage.reportPaths=coverage.xml
