sonar.projectKey=wesleykirkland_terraform-provider-urllo
sonar.organization=wesleykirkland

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/.terraform/**,examples/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
