#!/usr/bin/env python3
# Copyright (c) Wesley Kirkland-Daily
# SPDX-License-Identifier: MPL-2.0

"""Unit tests for check_docs.py.

Run via `make test-py`, or directly with:
    python3 -m unittest scripts.test_check_docs -v
Each test builds a small synthetic repo tree under a TemporaryDirectory
rather than touching the real repository, so these stay fast and don't
depend on (or corrupt) this repo's actual README/docs state.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent))

import check_docs  # noqa: E402


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


RESOURCE_GO = """\
package provider

func (r *ExampleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
\tresp.TypeName = req.ProviderTypeName + "_%s"
}
"""

DOC_HEADER = """\
---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "urllo_%s"
---

# doc body
"""


class TempRepo:
    """A minimal synthetic repo tree that satisfies check_docs's assumptions."""

    def __init__(self, root: Path) -> None:
        self.root = root

    def add_resource(self, suffix: str, *, with_type_name: bool = True) -> None:
        content = RESOURCE_GO % suffix if with_type_name else "package provider\n"
        write(self.root / "internal" / "provider" / f"{suffix}_resource.go", content)

    def add_data_source(self, suffix: str) -> None:
        write(self.root / "internal" / "provider" / f"{suffix}_data_source.go", RESOURCE_GO % suffix)

    def add_resource_doc(self, suffix: str) -> None:
        write(self.root / "docs" / "resources" / f"{suffix}.md", DOC_HEADER % suffix)

    def add_data_source_doc(self, suffix: str) -> None:
        write(self.root / "docs" / "data-sources" / f"{suffix}.md", DOC_HEADER % suffix)

    def set_readme(self, content: str) -> None:
        write(self.root / "README.md", content)

    def set_provider_go(self, content: str) -> None:
        write(self.root / "internal" / "provider" / "provider.go", content)

    def set_tf_readme(self, content: str) -> None:
        write(self.root / "terraform" / "README.md", content)

    def add_tf_file(self, name: str) -> None:
        write(self.root / "terraform" / name, "# tf file\n")


@contextmanager
def temp_repo() -> Iterator[TempRepo]:
    with tempfile.TemporaryDirectory() as tmp:
        yield TempRepo(Path(tmp))


class CheckResourcesAndDataSourcesTest(unittest.TestCase):
    def test_fully_documented_resource_passes(self) -> None:
        with temp_repo() as repo:
            repo.add_resource("rule")
            repo.add_resource_doc("rule")
            readme = "See [urllo_rule](docs/resources/rule.md) for details."
            failures = check_docs.check_resources_and_data_sources(repo.root, readme)
            self.assertEqual(failures, [])

    def test_missing_generated_doc_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.add_resource("rule")
            readme = "See [urllo_rule](docs/resources/rule.md) for details."
            failures = check_docs.check_resources_and_data_sources(repo.root, readme)
            self.assertEqual(len(failures), 1)
            self.assertIn("docs/resources/rule.md", failures[0])
            self.assertIn("no generated doc", failures[0])

    def test_missing_readme_link_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.add_resource("rule")
            repo.add_resource_doc("rule")
            failures = check_docs.check_resources_and_data_sources(repo.root, "README with no link")
            self.assertEqual(len(failures), 1)
            self.assertIn("does not link", failures[0])

    def test_missing_type_name_line_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.add_resource("rule", with_type_name=False)
            failures = check_docs.check_resources_and_data_sources(repo.root, "")
            self.assertEqual(len(failures), 1)
            self.assertIn("can't determine its type name", failures[0])

    def test_data_source_uses_data_sources_directory(self) -> None:
        with temp_repo() as repo:
            repo.add_data_source("hosts")
            repo.add_data_source_doc("hosts")
            readme = "[urllo_hosts](docs/data-sources/hosts.md)"
            failures = check_docs.check_resources_and_data_sources(repo.root, readme)
            self.assertEqual(failures, [])
            # Sanity: the doc must be expected under data-sources/, not resources/.
            self.assertFalse((repo.root / "docs" / "resources" / "hosts.md").exists())


class CheckProviderConfigTest(unittest.TestCase):
    def test_documented_attribute_passes(self) -> None:
        with temp_repo() as repo:
            repo.set_provider_go('"api_key": schema.StringAttribute{\n')
            failures = check_docs.check_provider_config(repo.root, "the `api_key` setting")
            self.assertEqual(failures, [])

    def test_undocumented_attribute_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.set_provider_go('"api_key": schema.StringAttribute{\n')
            failures = check_docs.check_provider_config(repo.root, "no mention here")
            self.assertEqual(len(failures), 1)
            self.assertIn("api_key", failures[0])


class CheckTerraformExamplesTest(unittest.TestCase):
    def test_mentioned_file_passes(self) -> None:
        with temp_repo() as repo:
            repo.add_tf_file("provider.tf")
            repo.set_tf_readme("Uses `provider.tf` for setup.")
            failures = check_docs.check_terraform_examples(repo.root)
            self.assertEqual(failures, [])

    def test_unmentioned_file_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.add_tf_file("provider.tf")
            repo.set_tf_readme("Nothing relevant here.")
            failures = check_docs.check_terraform_examples(repo.root)
            self.assertEqual(len(failures), 1)
            self.assertIn("provider.tf", failures[0])


class RepoRootTest(unittest.TestCase):
    def test_returns_this_checkout_root(self) -> None:
        # Runs for real (no mocking) since the test suite itself always
        # executes inside an actual git checkout.
        root = check_docs.repo_root()
        self.assertTrue((root / ".git").exists())
        self.assertTrue((root / "scripts" / "check_docs.py").is_file())


class CheckMarkdownFormatTest(unittest.TestCase):
    def test_missing_referenced_file_is_skipped_not_errored(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\nok\n")
            # terraform/README.md deliberately left absent.
            failures = check_docs.check_markdown_format(repo.root)
            self.assertEqual(failures, [])

    def test_well_formed_file_passes(self) -> None:
        with temp_repo() as repo:
            repo.set_readme(
                "# Title\n\n"
                "| A | B |\n"
                "| - | - |\n"
                "| 1 | 2 |\n\n"
                "[link](terraform/README.md)\n"
            )
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertEqual(failures, [])

    def test_unbalanced_fence_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\n```hcl\nfoo = 1\n")
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertTrue(any("unbalanced" in f for f in failures))

    def test_ragged_table_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\n| A | B |\n| - | - |\n| 1 | 2 | 3 |\n")
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertTrue(any("table row has" in f for f in failures))

    def test_broken_relative_link_is_reported(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\n[nowhere](docs/does-not-exist.md)\n")
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertTrue(any("does not resolve" in f for f in failures))

    def test_pipes_inside_fenced_code_are_ignored(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\n```hcl\n| this looks like a table row |\n```\n")
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertEqual(failures, [])

    def test_external_and_anchor_links_are_ignored(self) -> None:
        with temp_repo() as repo:
            repo.set_readme("# Title\n\n[ext](https://example.com/x)\n\n[anchor](#title)\n")
            repo.set_tf_readme("ok\n")
            failures = check_docs.check_markdown_format(repo.root)
            self.assertEqual(failures, [])


class CheckGeneratedHeadersTest(unittest.TestCase):
    def test_header_present_passes(self) -> None:
        with temp_repo() as repo:
            repo.add_resource_doc("rule")
            failures = check_docs.check_generated_headers(repo.root)
            self.assertEqual(failures, [])

    def test_header_missing_is_reported(self) -> None:
        with temp_repo() as repo:
            write(repo.root / "docs" / "resources" / "rule.md", "# hand-written, not generated\n")
            failures = check_docs.check_generated_headers(repo.root)
            self.assertEqual(len(failures), 1)
            self.assertIn("hand-edited", failures[0])

    def test_no_docs_directory_is_not_an_error(self) -> None:
        with temp_repo() as repo:
            failures = check_docs.check_generated_headers(repo.root)
            self.assertEqual(failures, [])


def build_fully_valid_repo(repo: TempRepo) -> None:
    repo.add_resource("rule")
    repo.add_resource_doc("rule")
    repo.set_provider_go('"api_key": schema.StringAttribute{\n')
    repo.add_tf_file("provider.tf")
    repo.set_tf_readme("Uses `provider.tf`.\n")
    repo.set_readme(
        "# Title\n\nthe `api_key` setting\n\n[urllo_rule](docs/resources/rule.md)\n"
    )


class RunAllChecksAndMainTest(unittest.TestCase):
    def test_run_all_checks_on_valid_repo_returns_no_failures(self) -> None:
        with temp_repo() as repo:
            build_fully_valid_repo(repo)
            failures = check_docs.run_all_checks(repo.root)
            self.assertEqual(failures, [])

    def test_main_returns_zero_on_valid_repo(self) -> None:
        with temp_repo() as repo:
            build_fully_valid_repo(repo)
            with mock.patch.object(check_docs, "repo_root", return_value=repo.root):
                self.assertEqual(check_docs.main(), 0)

    def test_main_returns_one_on_broken_repo(self) -> None:
        with temp_repo() as repo:
            repo.add_resource("rule")  # no doc, no readme link
            repo.set_provider_go("")
            repo.add_tf_file("provider.tf")
            repo.set_tf_readme("nothing mentioned\n")
            repo.set_readme("nothing here\n")
            with mock.patch.object(check_docs, "repo_root", return_value=repo.root):
                self.assertEqual(check_docs.main(), 1)


if __name__ == "__main__":
    unittest.main()
